# Generated by Django 2.2.6 on 2020-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upneed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upName', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
                ('dTail', models.TextField(max_length=400)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upNeed_info',
            },
        ),
        migrations.CreateModel(
            name='upthing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Thing_own', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='img')),
                ('image1', models.ImageField(upload_to='img')),
                ('link', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('dtail', models.TextField(max_length=400)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'thing_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('i_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'person_info',
            },
        ),
        migrations.CreateModel(
            name='Yzm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yzm', models.IntegerField(default=0)),
            ],
        ),
    ]
